name: Build LaTeX
on:
  push:
    branches:
      - main
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install LaTeX
        run: sudo apt-get install -y texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra
      - name: Compile LaTeX document
        run: pdflatex your-document.tex
      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: Compiled-PDF
          path: ./compiled_document.pdf